### ISSUE TITLE
Wrong type mapping

### ISSUE THREAD

**Issue by 0xHexE** [ivk1800/tdlib-dart#30]
```
E/flutter (13978): [ERROR:flutter/runtime/dart_isolate.cc(1315)] Unhandled exception:
E/flutter (13978): type 'Null' is not a subtype of type 'bool' in type cast
E/flutter (13978): #0      UserTypeBot.fromJson (package:tdlib/src/api/objects/user_type_bot.dart:72:47)
E/flutter (13978): #1      UserType.fromJson (package:tdlib/src/api/objects/user_type.dart:25:28)
E/flutter (13978): #2      User.fromJson (package:tdlib/src/api/objects/user.dart:179:22)
E/flutter (13978): #3      UpdateUser.fromJson (package:tdlib/src/api/objects/update_user.dart:24:18)
E/flutter (13978): #4      ConvertExtensions.toTdObject (package:tdlib/src/api/extensions/convert_extensions.dart:3460:27)
E/flutter (13978): #5      receiveIsolateEntryPoint (package:tdlib/src/client/platform/io/receive_isolate_endpoint.dart:21:34)
E/flutter (13978): <asynchronous suspension>
```

```dart
return UserTypeBot(
      canBeEdited: json['can_be_edited'] as bool,
      canJoinGroups: json['can_join_groups'] as bool,
      canReadAllGroupMessages: json['can_read_all_group_messages'] as bool,
      hasMainWebApp: json['has_main_web_app'] as bool, // problem lies here. has_main_web_app not availabe in the json.
      isInline: json['is_inline'] as bool,
      inlineQueryPlaceholder: json['inline_query_placeholder'] as String,
      needLocation: json['need_location'] as bool,
      canConnectToBusiness: json['can_connect_to_business'] as bool,
      canBeAddedToAttachmentMenu:
          json['can_be_added_to_attachment_menu'] as bool,
      activeUserCount: json['active_user_count'] as int,
    );
```

**Comment by ivk1800** [comment]
You can fix it in generator https://github.com/ivk1800/tdlib-generator

**Comment by ivk1800** [comment]
In the [schema ](https://github.com/tdlib/td/blob/53acb2b5343511432db5aa2091937c3d294c7faa/td/generate/scheme/td_api.tl#L585C1-L585C58) this field cannot be null
`//@has_main_web_app True, if the bot has the main Web App`
In [generator ](https://github.com/ivk1800/tdlib-generator/blob/794f49c80f916ad8ad29707588321ab53b7ab7d9/lib/src/parser.dart#L200)keywords is checked.
